### @RequestMapping 注解请求测试
POST {{baseUrl}}/springmvc/useRequestMapping?name=1

### @RequestParam 注解测试1 请求参数封装到基础数据类型
GET {{baseUrl}}/useParam1?age=18&name=我是名称

### @RequestParam 注解测试2 请求参数封装到对象类型参数
GET {{baseUrl}}/useParam2?id=1&username=我是名称&password=12334&age=12&gender=男

### @InitBinder、@ControllerAdvice 注解测试 请求参数日期字符串转换成日期类型
GET {{baseUrl}}/useInitBinder?id=1&username=我是名称&password=12334&age=12&gender=男&birthday=2020-10-10

### @RequestHeader 注解测试
GET {{baseUrl}}/useRequestHeader
# 设置header的属性
Accept-Language: zh_cn; I am MooN

### @CookieValue 注解测试
GET {{baseUrl}}/useCookieValue
Cookie: springmvc_sample=i_am_cookie?

### @ModelAttribute 注解测试
GET {{baseUrl}}/useModelAttribute?name=MooNkirA

### @SessionAttributes 注解测试(好像与下面请求@SessionAttribute测试无法为同一个会话，暂时只能在页面测试)
GET {{baseUrl}}/useSessionAttributes

### @SessionAttribute 注解测试
GET {{baseUrl}}/useSessionAttribute

### @ExceptionHandler 注解测试
GET {{baseUrl}}/useExceptionHandler?age=130

### @RequestBody 注解测试
# 此x-www-form-urlencoded类型spring mvc可以直接封装对象中
#POST {{baseUrl}}/useRequestBody
#Content-Type: application/x-www-form-urlencoded
#
#username=MooNkirA&age=18&gender=male

# 此application/json类型，json格式的数据是存在请求体中，spring mvc不能直接获取绑定到方法形参中
# 需要通过RequestBody注解，才能获取
POST {{baseUrl}}/useRequestBody
Content-Type: application/json

{
  "username": "MooNkirA",
  "age": 18,
  "ts": "male"
}

### @ResponseBody 注解标识在方法上测试
GET {{baseUrl}}/useRequestBodyOnMethod

### @EResponseBody 注解标识在类上测试
GET {{baseUrl}}/useResponseBodyOnClass

### @RestController 注解测试
GET {{baseUrl}}/useRestController

### @RestControllerAdvice 注解测试
# 测试前，将ExceptionHandlerAdvice异常处理类中的RestControllerAdvice注解与相应方法的注释放开
GET {{baseUrl}}/useRestControllerAdvice

###
