### @RequestMapping 注解请求测试
POST {{baseUrl}}/springmvc/useRequestMapping?name=1

### @RequestParam 注解测试1 请求参数封装到基础数据类型
GET {{baseUrl}}/useParam1?age=18&name=我是名称

### @RequestParam 注解测试2 请求参数封装到对象类型参数
GET {{baseUrl}}/useParam2?id=1&username=我是名称&password=12334&age=12&gender=男

### @InitBinder、@ControllerAdvice 注解测试 请求参数日期字符串转换成日期类型
GET {{baseUrl}}/useInitBinder?id=1&username=我是名称&password=12334&age=12&gender=男&birthday=2020-10-10

### @RequestHeader 注解测试
GET {{baseUrl}}/useRequestHeader
# 设置header的属性
Accept-Language: zh_cn; I am MooN

### @CookieValue 注解测试
GET {{baseUrl}}/useCookieValue
Cookie: springmvc_sample=i_am_cookie?

### @ModelAttribute 注解测试
GET {{baseUrl}}/useModelAttribute?name=MooNkirA

### @SessionAttributes 注解测试(好像与下面请求@SessionAttribute测试无法为同一个会话，暂时只能在页面测试)
GET {{baseUrl}}/useSessionAttributes

### @SessionAttribute 注解测试
GET {{baseUrl}}/useSessionAttribute

### @ExceptionHandler 注解测试
GET {{baseUrl}}/useExceptionHandler?age=130

###
